checking low severity

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -57,17 +57,14 @@ jobs:
 
       - name: Check Trivy Scan Results
         run: |
-          # Print the structure of the SARIF file
-          jq . results.sarif
-      
-          # Count the occurrences of CRITICAL severity
-          CRITICAL_COUNT=$(jq -r '.runs[].tool.driver.rules | select(.!=null) | map(select(.properties.severity == "CRITICAL")) | length' results.sarif)
-          if [ $CRITICAL_COUNT -gt 0 ]; then
-            echo "Trivy detected $CRITICAL_COUNT critical vulnerabilities. Failing the build."
-            exit 1
+          LOW_COUNT=$(jq -r '.runs[].results | select(.!=null) | .[].properties.severity | select(.=="LOW")' results.sarif | wc -l)
+          if [ $LOW_COUNT -gt 0 ]; then
+              echo "Trivy detected $LOW_COUNT low-severity vulnerabilities. Failing the build."
+              exit 1
           else
-            echo "Trivy scan passed without critical vulnerabilities."
+              echo "Trivy scan passed without low-severity vulnerabilities."
           fi
+
 
 
 
