condition-error3

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -49,15 +49,28 @@ jobs:
       #     output: 'results.sarif'
       #     exit-code: '1'
       #     ignore-unfixed: true
-      - name: Check Trivy Scan Results
-        run: cat results.sarif
+      # - name: Check Trivy Scan Results
+      #   run: cat results.sarif
         
       - name: Upload Trivy scan results to GitHub Security tab
         uses: github/codeql-action/upload-sarif@v3
         with:
          sarif_file: 'results.sarif'
 
+      - name: Check Trivy Scan Results
+        run: |
+          # Print the structure of the SARIF file
+          jq . results.sarif
       
+          # Count the occurrences of CRITICAL severity
+          CRITICAL_COUNT=$(jq -r '.runs[].tool.driver.rules | select(.!=null) | map(select(.properties.severity == "LOW")) | length' results.sarif)
+          if [ $CRITICAL_COUNT -gt 0 ]; then
+            echo "Trivy detected $CRITICAL_COUNT critical vulnerabilities. Failing the build."
+            exit 1
+          else
+            echo "Trivy scan passed without critical vulnerabilities."
+          fi
+
 
 
 
