executing grep command

diff --git a/.github/workflows/trivy-scan.yml b/.github/workflows/trivy-scan.yml
--- a/.github/workflows/trivy-scan.yml
+++ b/.github/workflows/trivy-scan.yml
@@ -53,19 +53,20 @@ jobs:
          sarif_file: 'results.sarif'
 
       - name: Check Trivy Scan Results
-        run: |
-          # Print the structure of the SARIF file
-          # jq . results.sarif
+        run: cat results.sarif | grep LOW
+          # # Print the structure of the SARIF file
+          # # jq . results.sarif
       
-          CRITICAL_COUNT=$(jq -r '.runs[].tool.driver.rules | select(.!=null) | map(select(.properties.severity == "LOW")) | length' results.sarif)
-          echo $CRITICAL_COUNT
           
-          if [ $CRITICAL_COUNT -gt 0 ]; then
-            echo "Trivy detected $CRITICAL_COUNT critical vulnerabilities. Failing the build."
-            exit 1
-          else
-            echo "Trivy scan passed without critical vulnerabilities."
-          fi
+          # # CRITICAL_COUNT=$(jq -r '.runs[].tool.driver.rules | select(.!=null) | map(select(.properties.severity == "LOW")) | length' results.sarif)
+          # # echo $CRITICAL_COUNT
+          
+          # if [ $CRITICAL_COUNT -gt 0 ]; then
+          #   echo "Trivy detected $CRITICAL_COUNT critical vulnerabilities. Failing the build."
+          #   exit 1
+          # else
+          #   echo "Trivy scan passed without critical vulnerabilities."
+          # fi
 
 
 
