token testing5

diff --git a/.github/workflows/trivy-scan.yml b/.github/workflows/trivy-scan.yml
--- a/.github/workflows/trivy-scan.yml
+++ b/.github/workflows/trivy-scan.yml
@@ -18,9 +18,49 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
         with:
-          token: ${{ secrets.TRIVY_ACCESS }}
+          token: ${{ secrets.TRIVY_ACCESS }}  
 
-      # - name: Install trivy
+      - name: Run Trivy vulnerability scanner in repo mode
+        uses: aquasecurity/trivy-action@0.16.1
+        with:
+          scan-type: 'fs'
+          ignore-unfixed: true
+          format: 'sarif'
+          output: 'results.sarif'
+          severity: 'LOW'
+          # exit-code: 1
+
+      # - name: Check Trivy Scan Results
+      #   run: cat results.sarif
+        
+      - name: Upload Trivy scan results to GitHub Security tab
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          name: Scanning Results
+          sarif_file: results.sarif
+          token: ${{ secrets.TRIVY_ACCESS }}
+      
+      - name: Count LOW occurrences
+        id: count_low
+        run: |
+          CRITICAL_COUNT=$(cat results.sarif | grep -c CRITICAL || true)
+          echo "CRITICAL_COUNT=$CRITICAL_COUNT" >> $GITHUB_ENV
+
+      - name: Display CRITICAL_COUNT
+        run: |
+          echo "CRITICAL_COUNT is $CRITICAL_COUNT"
+
+      - name: Check for Critical Vulnerabilities
+        run: |
+          if [ $CRITICAL_COUNT -gt 0 ]; then
+            echo "Trivy detected $CRITICAL_COUNT critical vulnerabilities. Failing the build."
+            exit 1
+          else
+            echo "Trivy scan passed without critical vulnerabilities."
+          fi
+
+
+          # - name: Install trivy
       #   run: |
       #     sudo apt-get install wget apt-transport-https gnupg lsb-release
       #     wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
@@ -52,45 +92,3 @@ jobs:
       #     image-ref: nginx:latest
       #     format: json
       #     output: results.json
-      
-
-      - name: Run Trivy vulnerability scanner in repo mode
-        uses: aquasecurity/trivy-action@0.16.1
-        with:
-          scan-type: 'fs'
-          ignore-unfixed: true
-          format: 'sarif'
-          output: 'results.sarif'
-          severity: 'LOW'
-          # exit-code: 1
-
-      # - name: Check Trivy Scan Results
-      #   run: cat results.sarif
-        
-      - name: Upload Trivy scan results to GitHub Security tab
-        uses: github/codeql-action/upload-sarif@v3
-        with:
-          name: Scanning Results
-          sarif_file: results.sarif
-      
-      - name: Count LOW occurrences
-        id: count_low
-        run: |
-          CRITICAL_COUNT=$(cat results.sarif | grep -c CRITICAL || true)
-          echo "CRITICAL_COUNT=$CRITICAL_COUNT" >> $GITHUB_ENV
-
-      - name: Display CRITICAL_COUNT
-        run: |
-          echo "CRITICAL_COUNT is $CRITICAL_COUNT"
-
-      - name: Check for Critical Vulnerabilities
-        run: |
-          if [ $CRITICAL_COUNT -gt 0 ]; then
-            echo "Trivy detected $CRITICAL_COUNT critical vulnerabilities. Failing the build."
-            exit 1
-          else
-            echo "Trivy scan passed without critical vulnerabilities."
-          fi
-
-
-
